### ISSUE TITLE
Null pointer Exception

### ISSUE THREAD

**Issue by szlwzl** [chrismattmann/imagecat#32]
I am receiving the below error in oodt.out after running $OODT_HOME/bin/chunker. Tomcat and Solr both appear to be starting correctly and the path to images is correct in the roxy file. I have also set permissions liberally for the image files but am unable to get any results. Images are all jpegs with no spaces or special chars.

```
Sep 16, 2015 1:25:25 PM org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread checkTaskRequiredMetadata
INFO: Task: [Chunker] has no required metadata fields
Exception in thread "Thread-4" java.lang.NullPointerException: value cannot be null
    at org.apache.lucene.document.Field.<init>(Field.java:240)
    at org.apache.lucene.document.Field.<init>(Field.java:216)
    at org.apache.oodt.cas.workflow.instrepo.LuceneWorkflowInstanceRepository.addInstanceMetadataToDoc(LuceneWorkflowInstanceRepository.java:576)
    at org.apache.oodt.cas.workflow.instrepo.LuceneWorkflowInstanceRepository.toDoc(LuceneWorkflowInstanceRepository.java:543)
    at org.apache.oodt.cas.workflow.instrepo.LuceneWorkflowInstanceRepository.addWorkflowInstanceToCatalog(LuceneWorkflowInstanceRepository.java:459)
    at org.apache.oodt.cas.workflow.instrepo.LuceneWorkflowInstanceRepository.updateWorkflowInstance(LuceneWorkflowInstanceRepository.java:200)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.persistWorkflowInstance(IterativeWorkflowProcessorThread.java:563)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.run(IterativeWorkflowProcessorThread.java:258)
    at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by chrismattmann** [comment]
Hi @szlwzl - can you show me the output of:

```
cd $OODT_HOME/workflow/bin
./wmgr-client --url $WORKFLOW_URL --operation --getWorkflowInsts
```

What i'm looking for is the instance ID of the Chunker task. You can also get this from the OPSUI if that helps too. Once you have the ID, can you then run this command, and show me the output:

```
./wmgr-client --url $WORKFLOW_URL --operation --getWorkflowInstMet --id <the ID of the Chunker inst>
```

**Comment by szlwzl** [comment]
Hi @chrismattmann,

Thanks for the assist with this - I've just run the first of the commands and am getting:

```
org.apache.xmlrpc.XmlRpcException: org.apache.xmlrpc.XmlRpcException: null values not supported by XML-RPC
    at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeException(XmlRpcClientResponseProcessor.java:104)
    at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeResponse(XmlRpcClientResponseProcessor.java:71)
    at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:73)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:194)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:185)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:178)
    at org.apache.oodt.cas.workflow.system.XmlRpcWorkflowManagerClient.getWorkflowInstances(XmlRpcWorkflowManagerClient.java:667)
    at org.apache.oodt.cas.workflow.cli.action.GetWorkflowInstsCliAction.execute(GetWorkflowInstsCliAction.java:42)
    at org.apache.oodt.cas.cli.CmdLineUtility.execute(CmdLineUtility.java:331)
    at org.apache.oodt.cas.cli.CmdLineUtility.run(CmdLineUtility.java:187)
    at org.apache.oodt.cas.workflow.system.XmlRpcWorkflowManagerClient.main(XmlRpcWorkflowManagerClient.java:692)
ERROR: Failed to get workflow instances from URL 'http://localhost:9001' : org.apache.xmlrpc.XmlRpcException: null values not supported by XML-RPC
```

**Comment by szlwzl** [comment]
I switched over to debian 8 from centos6.7 and now it's working like a charm :)

**Comment by chrismattmann** [comment]
Gotcha! Maybe it's the Java version what Java version is on each? Great to hear regardless
